function [projectRoot, folders] = project_paths()
%project_paths   Define the set of folders to add to the MATLAB path.
%   Subfolders are automatically added.
%
%   @author Moritz Ulmer<moritz.ulmer@posteo.de>
%   @created 15.12.2015
%   @updated 9.7.2015

folders = { ...
    'backup', ...
    'data', ...
    'guis', ...
    'models', ...
    'src', ...
    'tests', ...
    'users', ...
    'utilities', ...
    'work' ...
    };

% Use Simulink Project API to get the current project (API changed in R2013a):
if(version <= 8.0) % Equal or older than R2012b
    p = Simulink.ModelManagement.Project.CurrentProject;
    projectRoot = p.getRootFolder;
else % Equal or newer than R2013a
    p = slproject.getCurrentProject;
    projectRoot = p.RootFolder;
end

end